### ISSUE TITLE
Beehives and bee nests are facing the wrong direction

### ISSUE THREAD

**Issue by AryToNeX** [GeyserMC/mappings#38]
Specifically, they seem to be facing always the opposite way in Bedrock (so the bees always come out from behind).

Tested on Geyser version 9b3cd8f725ff26e6a0abfd87481f021d959a9be6 and PaperMC 1.16.3 version git-Paper-229

**Comment by AryToNeX** [comment]
@E404NNF there isn't any for this specific repo

**Comment by E404NNF** [comment]
> @E404NNF there isn't any for this specific repo

Oh sorry throught this is the Geyser repo, sorry

**Comment by DoctorMacc** [comment]
This will be fixed with the 1.16.100 Bedrock update.

**Comment by DoctorMacc** [comment]
This will be fixed.
