### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by extremeheat** [GeyserMC/mappings#42]
Hey, I'd like to add some of these mappings over to [PrismarineJS/minecraft-data](https://github.com/PrismarineJS/minecraft-data) (MIT). However there's no license file in the repo, so it would be nice to add one.

**Comment by DoctorMacc** [comment]
Hello! Until we are able to re-license this, I can point you to https://github.com/CloudburstMC/ProxyPass/ - it has a proper license, and we use it to generate the block palette and item palette. You can also use https://github.com/bundabrg/McReverse to generate the block palette for 1.16.100 in the NBT file format - if you'd like, I can get in touch with that contributor and have that project licensed.

**Comment by RednedEpic** [comment]
This project is now under the MIT license.
