### ISSUE TITLE
Nether Bricks (Block) showing as Nether Brick (Item) to Bedrock players

### ISSUE THREAD

**Issue by Technoguyfication** [GeyserMC/mappings#61]
When a Bedrock player is given a `nether_brick`, it shows as a `nether_bricks` to the Bedrock player. Attempts to place the block fail, and the item is ghosted in the player's inventory until they relog. I believe this is because `nether_brick` (Java) is being mapped to `nether_brick` (Bedrock), when it should be mapped to `netherbrick` as that is the ID of the corresponding item in Bedrock edition.

**Comment by Konicai** [comment]
I thought I fixed this :(

**Comment by Technoguyfication** [comment]
> I thought I fixed this :(

Oh shoot, I'm actually on a pretty old version of Geyser. I'll update and report back if it fixes it.

**Comment by Technoguyfication** [comment]
This was fixed by updating, thanks!
