### ISSUE TITLE
Incorrect leaves and missing mappings

### ISSUE THREAD

**Issue by DrAv0011** [GeyserMC/mappings#65]
In "minecraft:oak_leaves[distance=1,persistent=true]"
inside bedrock_states persistent bit is set to false when in the block id says is true

Also it is the only leave id where update bit is set to true so if looking for a mapping checking for equal bedrock_states and leaves have the update_bit to true it will never match

**Comment by Camotoy** [comment]
I don't believe this visually affects anything?

**Comment by Konicai** [comment]
Yeah, its basically only data the server uses

**Comment by RednedEpic** [comment]
This is likely nothing anyone is going to fix on our end and it has no effect on the actual block state itself as this is just a value the server relies on. Feel free to open a PR, but it's not really worth our effort fixing this.
